version: '3'

services:
  web:
    build: .
    command: gunicorn SWE_BE.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=software_engineering_be_user
      - POSTGRES_PASSWORD=software_engineering_be_password
      - POSTGRES_DB=software_engineering_be_dev
volumes:
  postgres_data: