# Generated by Django 3.2.16 on 2022-11-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.TextField(primary_key=True, serialize=False)),
                ('userPW', models.TextField()),
                ('userName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InterestPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantID', models.TextField()),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PT.user')),
            ],
        ),
    ]
